# Generated by Django 4.2.11 on 2024-03-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tatus',
            new_name='status',
        ),
    ]
